# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a014657f023cea662d93f3cef7dbdd32896190cfb37ad064173984fef9fc60a6a551e3963a7735d7b10cb7067e4768aa38c89913ea3679d22b5992365f012b09

test:
  secret_key_base: 470c67517ade68858a64852be031f804bbaabb537ce00c878f6a168d8905cdfce3b7a688d77b29f437ac0de3753f4c620b833aca6fb53c726b1e1004204e3b99

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
